version: '3'
services:

  web:
    build:
      context: ./docker/
      args:
        version: '4.0.2'
    ports:
      - 80:80
    volumes:
      - ./BeGateway:/var/www/app/BeGateway
      - okaycms-html:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_DATABASE: 'okaycms'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - okaycms-db:/var/lib/mysql

volumes:
  okaycms-db:
  okaycms-html:
